#!/usr/bin/env python3
"""theory/liveness.py -- working memory as register pressure, tried on the HW1 run.  Stdlib only.

Model (theory/RECORD-THEORY.md, section 5). A task moves information between surfaces. An item is PRODUCED where the
person first gets it (read in the chat, seen in a list) and CONSUMED where it is needed (the file to pick, the view to
open, the step order). Between the two it is LIVE and must be carried, unless the surface it is needed on shows it
again (REMATERIALISED: no memory needed). Pressure at a step = number of live, non-rematerialised items. Where pressure
exceeds the budget B, the model predicts a SPILL: some item is lost and must be fetched again (a RELOAD) or rediscovered.

What is encoded by hand here (the transcriber): the items, where each is produced and consumed, and which surfaces
rematerialise it. In use these come from the task's design and the artifact (which information crosses surfaces, what
each screen shows), not from the person. The narrator's reports of losing track are HELD OUT and only compared.
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EV = ROOT / "docs/evidence/hw1-correction-2026-10-03"
STEPS = [json.loads(l) for l in (EV / "transcription.jsonl").read_text(encoding="utf-8").splitlines() if l.strip()]
RUN = [s for s in STEPS if s.get("scope", "2026-10-03") == "2026-10-03" and s.get("kind") in ("step", "event", "goal")]
POS = {s["id"]: i for i, s in enumerate(RUN)}

# items: id -> (produced at, consumed at, rematerialised at, what) ; ids are transcription steps of this run
ITEMS = {
    "goal":   ("D",   "H",  set(),            "the task itself: load the corrections, scan, apply"),
    "loaded": ("D3",  "E8", set(),            "whether the corrections are loaded (believed true from D3)"),
    "file":   ("E3d", "E8", set(),            "which file: corrections / hw1 / json (three keys, held as one chunk)"),
    "view":   ("E3",  "E7", set(),            "which view to use after loading: Re-sync"),
    "order":  ("E3",  "G5", {"E9"},           "the step order: load, then Scan, then Apply"),
    "seen":   ("E1",  "E2", set(),            "options already ruled out while paging the folder"),
    "where":  ("G1",  "G4", set(),            "where in the list Apply was, and how many were done"),
}
# narrator-reported losses (held out): steps where the account says the goal or an item was lost or rediscovered
REPORTED = {"E2": "我又开始忘记我是来干嘛的了", "E3": "重新加载行动终极目的", "E9": "不对，还要Scan啊",
            "G4": "又开始一个一个读chip了", "G5": "再次突然发现自己还要再scan一遍"}

def live_at(i):
    out = []
    for k, (p, c, remat, _) in ITEMS.items():
        if p in POS and c in POS and POS[p] <= i <= POS[c] and RUN[i]["id"] not in remat:
            out.append(k)
    return out

def run(B):
    pred = []
    for i, s in enumerate(RUN):
        L = live_at(i)
        if len(L) > B: pred.append((s["id"], len(L), L))
    return pred

if __name__ == "__main__":
    lines = ["# Liveness model on the HW1 run (generated by theory/liveness.py)", "",
             "Items carried between surfaces (encoded by hand from the task; in use they come from the task design):", "",
             "| item | produced | consumed | what |", "|---|---|---|---|"]
    for k, (p, c, r, w) in ITEMS.items():
        lines.append(f"| {k} | {p} | {c} | {w} |")
    lines += ["", "Pressure along the run (live items per step):", "", "| step | op | pressure | live |", "|---|---|---|---|"]
    for i, s in enumerate(RUN):
        L = live_at(i)
        lines.append(f"| {s['id']} | {s.get('op') or s.get('kind')} | {len(L)} | {', '.join(L)} |")
    lines += ["", "Predicted spills (pressure > B) against reported losses (held out):", "",
              "| B | predicted spill steps | reported losses | hits | misses (reported, not predicted) | false alarms |", "|---|---|---|---|---|---|"]
    goal_of = {s["id"]: s.get("parent") for s in STEPS}
    for B in (2, 3, 4):
        P = [x[0] for x in run(B)]
        # a reported loss is HIT if a spill is predicted at it or at a step in the same goal at most two steps before
        hits, misses = [], []
        for r in REPORTED:
            near = [p for p in P if goal_of.get(p) == goal_of.get(r) and 0 <= POS.get(r, 0) - POS.get(p, -99) <= 2] + ([r] if r in P else [])
            (hits if near else misses).append(r)
        fa = [p for p in P if not any(goal_of.get(p) == goal_of.get(r) and 0 <= POS.get(r, 0) - POS.get(p, 0) <= 2 for r in REPORTED)]
        lines.append(f"| {B} | {', '.join(P) or '-'} | {', '.join(REPORTED)} | {len(hits)} ({', '.join(hits)}) | {', '.join(misses) or '-'} | {len(fa)} |")
    out = "\n".join(lines) + "\n"
    (Path(__file__).parent / "LIVENESS.md").write_text(out, encoding="utf-8")
    print(out)
